/*
 * @Author: Jiu_xiao mcmrzy@163.com
 * @Date: 2023-11-01 13:15:07
 * @LastEditors: Jiu_xiao mcmrzy@163.com
 * @LastEditTime: 2023-11-01 15:40:12
 * @FilePath: \WeatherClockV1.0\src\screens\ui_Screen1.c
 * @Description: QQ:1924172518
 * 微信jiuxiaoweixin
 * Copyright (c) 2023 by Maoz, All Rights Reserved. 
 */
/*
 * @Author: Jiu_xiao mcmrzy@163.com
 * @Date: 2023-10-29 22:24:57
 * @LastEditors: Jiu_xiao mcmrzy@163.com
 * @LastEditTime: 2023-11-01 15:21:43
 * @FilePath: \WeatherClockV1.0\src\screens\ui_Screen1.c
 * @Description: QQ:1924172518
 * 微信jiuxiaoweixin
 * Copyright (c) 2023 by Maoz, All Rights Reserved. 
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project


#include "ui.h"



void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_align(ui_Screen1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_root = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_root, lv_pct(100));
lv_obj_set_height( ui_root, lv_pct(100));
lv_obj_set_align( ui_root, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_root, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_root, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_root, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_root, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_root, lv_color_hex(0x1F1E1E), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_root, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_City = lv_label_create(ui_root);
lv_obj_set_width( ui_City, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_City, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_City, -50 );
lv_obj_set_y( ui_City, -52 );
lv_obj_set_align( ui_City, LV_ALIGN_CENTER );
lv_label_set_text(ui_City,"xxx");
lv_obj_set_style_text_color(ui_City, lv_color_hex(0xFF9E06), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_City, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_City, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherlogo = lv_img_create(ui_root);
lv_img_set_src(ui_weatherlogo, &ui_img_594565377);
lv_obj_set_width( ui_weatherlogo, 48);
lv_obj_set_height( ui_weatherlogo, 48);
lv_obj_set_x( ui_weatherlogo, 13 );
lv_obj_set_y( ui_weatherlogo, -21 );
lv_obj_set_align( ui_weatherlogo, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_weatherlogo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_weatherlogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_weatherlogo,128);

ui_Temperature = lv_label_create(ui_root);
lv_obj_set_width( ui_Temperature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature, -30 );
lv_obj_set_y( ui_Temperature, -37 );
lv_obj_set_align( ui_Temperature, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature,"当前气温xx℃");
lv_obj_set_style_text_font(ui_Temperature, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time = lv_obj_create(ui_root);
lv_obj_set_width( ui_Time, 146);
lv_obj_set_height( ui_Time, 44);
lv_obj_set_x( ui_Time, -1 );
lv_obj_set_y( ui_Time, -6 );
lv_obj_set_align( ui_Time, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Time, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0xffa500), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Time, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_hour = lv_label_create(ui_Time);
lv_obj_set_width( ui_hour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hour, -50 );
lv_obj_set_y( ui_hour, 2 );
lv_obj_set_align( ui_hour, LV_ALIGN_CENTER );
lv_label_set_text(ui_hour,"00");
lv_obj_set_style_text_color(ui_hour, lv_color_hex(0xF94040), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_hour, &ui_font_jiangcheng40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minuate = lv_label_create(ui_Time);
lv_obj_set_width( ui_minuate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_minuate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_minuate, 1 );
lv_obj_set_y( ui_minuate, 2 );
lv_obj_set_align( ui_minuate, LV_ALIGN_CENTER );
lv_label_set_text(ui_minuate,"00");
lv_obj_set_style_text_color(ui_minuate, lv_color_hex(0x2355FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_minuate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_minuate, &ui_font_jiangcheng40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_second = lv_label_create(ui_Time);
lv_obj_set_width( ui_second, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_second, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_second, 43 );
lv_obj_set_y( ui_second, 11 );
lv_obj_set_align( ui_second, LV_ALIGN_CENTER );
lv_label_set_text(ui_second,"00");
lv_obj_set_style_text_color(ui_second, lv_color_hex(0x37E8D4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_second, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_second, &ui_font_jiangcheng20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weatherbox = lv_obj_create(ui_Time);
lv_obj_set_width( ui_weatherbox, 45);
lv_obj_set_height( ui_weatherbox, 22);
lv_obj_set_x( ui_weatherbox, 48 );
lv_obj_set_y( ui_weatherbox, -9 );
lv_obj_set_align( ui_weatherbox, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_weatherbox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_weatherbox, lv_color_hex(0xff4700), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_weatherbox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_weather = lv_label_create(ui_weatherbox);
lv_obj_set_width( ui_weather, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_weather, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_weather, LV_ALIGN_CENTER );
lv_label_set_text(ui_weather,"晴");
lv_obj_set_style_text_color(ui_weather, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_weather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_weather, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_week = lv_label_create(ui_root);
lv_obj_set_width( ui_week, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_week, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_week, 4 );
lv_obj_set_y( ui_week, 26 );
lv_obj_set_align( ui_week, LV_ALIGN_CENTER );
lv_label_set_text(ui_week,"周一");
lv_obj_set_style_text_color(ui_week, lv_color_hex(0x58F4AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_week, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_week, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Date = lv_label_create(ui_root);
lv_obj_set_width( ui_Date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Date, -41 );
lv_obj_set_y( ui_Date, 26 );
lv_obj_set_align( ui_Date, LV_ALIGN_CENTER );
lv_label_set_text(ui_Date,"1月1日");
lv_obj_set_style_text_color(ui_Date, lv_color_hex(0x58F4AA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Date, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp, -56 );
lv_obj_set_y( ui_temp, 39 );
lv_obj_set_align( ui_temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_temp,"温度");
lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temp, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -56 );
lv_obj_set_y( ui_Label15, 53 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"湿度");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = lv_bar_create(ui_Screen1);
lv_bar_set_range(ui_Bar1, -10,50);
lv_bar_set_value(ui_Bar1,28,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 26);
lv_obj_set_height( ui_Bar1, 3);
lv_obj_set_x( ui_Bar1, -28 );
lv_obj_set_y( ui_Bar1, 39 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_grad_color(ui_Bar1, lv_color_hex(0xE90000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_Bar1, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Bar1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Bar1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xF71B1B), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Bar2 = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_Bar2,80,LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 26);
lv_obj_set_height( ui_Bar2, 3);
lv_obj_set_x( ui_Bar2, -28 );
lv_obj_set_y( ui_Bar2, 54 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );
lv_obj_set_style_bg_grad_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_color(ui_Bar2, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Bar2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Bar2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x07E172), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 5 );
lv_obj_set_y( ui_Label16, 39 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"28℃");
lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label16, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 5 );
lv_obj_set_y( ui_Label1, 39 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"28℃");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 5 );
lv_obj_set_y( ui_Label2, 54 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"83%");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_jiangcheng12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image8, &gif4);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image8, 109 );
lv_obj_set_y( ui_Image8, 87 );
lv_obj_set_align( ui_Image8, LV_ALIGN_TOP_LEFT );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );
lv_img_set_pivot(ui_Image8,2,2);
lv_img_set_angle(ui_Image8,2);
lv_img_set_zoom(ui_Image8,64);

}
