// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif
#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_root;
extern lv_obj_t *ui_City;
extern lv_obj_t *ui_weatherlogo;
extern lv_obj_t *ui_Temperature;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_hour;
extern lv_obj_t *ui_minuate;
extern lv_obj_t *ui_second;
extern lv_obj_t *ui_weatherbox;
extern lv_obj_t *ui_weather;
extern lv_obj_t *ui_week;
extern lv_obj_t *ui_Date;
extern lv_obj_t *ui_temp;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_594565377);       //包含图片资源文件
LV_IMG_DECLARE(gif4);



LV_FONT_DECLARE(ui_font_jiangcheng12);
LV_FONT_DECLARE(ui_font_jiangcheng40);
LV_FONT_DECLARE(ui_font_jiangcheng20);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
